# Generated by Django 4.2.2 on 2023-06-19 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_test', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserAPIKey',
        ),
    ]
