# Generated by Django 4.2.2 on 2023-06-23 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_userapikey'),
    ]

    operations = [
        migrations.AddField(
            model_name='userapikey',
            name='create_date',
            field=models.DateField(auto_now=True),
        ),
    ]
