# Generated by Django 4.2.2 on 2023-06-23 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_userapikey_create_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userapikey',
            name='expiration_date',
            field=models.DateField(null=True),
        ),
    ]
