import Login from "./layouts/authentication/Login";
import Signup from "./layouts/authentication/Signup";
import MainLayout from "./layouts/main/MainLayout";
import Logout from "./layouts/authentication/Logout";
import Apikeyselect from "./layouts/test/apikeyselect";


const routes = [
    {
      type: "none",
      name: "MainLayout",
      key: "main-layout",
      route: "/",
    //   icon: <Shop size="12px" />,
      component: MainLayout,
      noCollapse: true,
      protected: false,
    },
    {
      type: "none",
      name: "Login",
      key: "login",
      route: "/authentication/login",
      // icon: <Document size="12px" />,
      component: Login,
      noCollapse: true,
      protected: false,
    },
    {
      type: "none",
      name: "Signup",
      key: "signup",
      route: "/authentication/signup",
      // icon: <SpaceShip size="12px" />,
      component: Signup,
      noCollapse: true,
      protected: false,
    },
    {
      type: "collapse",
      name: "Logout",
      key: "logout",
      route: "/authentication/logout",
      // icon: <SpaceShip size="12px" />,
      component: Logout,
      noCollapse: true,
    },
    {
      type: "collapse",
      name: "apikeyselect",
      key: "apikeyselect",
      route: "/test",
      // icon: <SpaceShip size="12px" />,
      component: Apikeyselect,
      noCollapse: true,
    },
        // {
    //   type: "collapse",
    //   name: "Dashboard",
    //   key: "dashboard",
    //   route: "/dashboard",
    //   icon: <Shop size="12px" />,
    //   component: Dashboard,
    //   noCollapse: true,
    //   protected: true,
    // },
    // {
    //   type: "collapse",
    //   name: "Tables",
    //   key: "tables",
    //   route: "/tables",
    //   icon: <Office size="12px" />,
    //   component: Tables,
    //   noCollapse: true,
    //   protected: true,
    // },
    // {
    //   type: "collapse",
    //   name: "Billing",
    //   key: "billing",
    //   route: "/billing",
    //   icon: <CreditCard size="12px" />,
    //   component: Billing,
    //   noCollapse: true,
    //   protected: true,
    // },
    // {
    //   type: "collapse",
    //   name: "Virtual Reality",
    //   key: "virtual-reality",
    //   route: "/virtual-reality",
    //   icon: <Cube size="12px" />,
    //   component: VirtualReality,
    //   noCollapse: true,
    //   protected: true,
    // },
    // {
    //   type: "collapse",
    //   name: "RTL",
    //   key: "rtl",
    //   route: "/rtl",
    //   icon: <Settings size="12px" />,
    //   component: RTL,
    //   noCollapse: true,
    //   protected: true,
    // },
    // { type: "title", title: "Account Pages", key: "account-pages" },
    // {
    //   type: "collapse",
    //   name: "Profile",
    //   key: "profile",
    //   route: "/profile",
    //   icon: <CustomerSupport size="12px" />,
    //   component: Profile,
    //   noCollapse: true,
    //   protected: true,
    // },
  ];
  
  export default routes;
  