# Generated by Django 4.2.2 on 2023-06-12 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_user', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
