# Generated by Django 4.2.2 on 2023-06-12 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_user', '0003_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='agreeDataProcessing',
            field=models.BooleanField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='agreePrivacyPolicy',
            field=models.BooleanField(blank=True, default=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='agreeTerms',
            field=models.BooleanField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.DateTimeField(auto_now_add=True, db_index=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(),
        ),
    ]
